CREATE TYPE user_role AS ENUM ('USER', 'ADMIN');

CREATE TYPE ad_status AS ENUM ('ACTIVE', 'CLOSED', 'DELETED');

CREATE TYPE notification_type AS ENUM ('EMAIL_CONFIRM', 'AD_ACTIVITY', 'RECOMMENDATION');